apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: find-coffee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: vup4k0806/find_coffee:latest
          command: ["uv", "run", "--no-sync", "celery", "-A", "core", "worker", "-l", "info"]
          envFrom:
            - configMapRef:
                name: find-coffee-config
            - secretRef:
                name: find-coffee-secret
