apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: find-coffee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
        - name: migrate
          image: vup4k0806/find_coffee:latest
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: find-coffee-config
            - secretRef:
                name: find-coffee-secret
      containers:
        - name: web
          image: vup4k0806/find_coffee:a6a0fb9
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: find-coffee-config
            - secretRef:
                name: find-coffee-secret
